settings:
  username: annasehgal
  commit_msg: "chore: update recent GitHub activity"
  max_lines: 5
  readme_file: README.md
  date:
    timezone: America/Los_Angeles
  disabled_events:
    - PushEvent
    - CreateEvent
    - DeleteEvent
